---
# ======================================================================
#       PLAY -- install a Cisco Secure Workload agent on a target host
#       in the inventory file
# ======================================================================

- name: install a Cisco Secure Workload agent
  hosts: all
  gather_facts: true
  become: yes
  remote_user: root
  become_method: sudo

  vars_prompt:
   - name: "csw_tenant"
     prompt: "Enter Tenant to install the agent in"
     private: no
     default: "duslab"

  roles:
    - csw-install